from flask import Flask, request
from flask_cors import CORS
import json, requests

app = Flask(__name__)
cors = CORS(app, resources={r"/*": {"origins": "*"}})
app.config['CORS_HEADERS'] = 'Content-Type'

"""
Server for Wyzefind API:
-Analyzes document
-Performs Cypher queries
-
"""

# TODO: Add memcache
# TODO: Change TOPIC to Topic in cypher


# The cloud function name is appended on to this
base_cloud_function = 'https://us-central1-ai-labs-226917.cloudfunctions.net/{0}'


def format_function_url(cloud_function):
    return base_cloud_function.format(cloud_function)


@app.route('/', methods=['POST'])
def generate():
    """
    Route takes the name of the cloud function from the post request:
    1. Calls correct cloud function to generate
    2. Passes args to call cloud functions

    Return the data generated by cloud function
    :return:
    """

    data = request.data
    data_dict = json.loads(data)

    try:
        cloud_function = data_dict["cloud_function"]
        function_args = data_dict["args"]
    except (KeyError):
        response = app.response_class(
            response='Proper parameter missing',
            status=400,
        )
        return response

    url = format_function_url(cloud_function)

    try:
        response = requests.post(url, json=function_args)
    except ConnectionError:
        response = 'Function not found'

    response = app.response_class(
        response=response.text,
        status=200,
        mimetype='application/json'
    )

    return response


@app.route('/', methods=['GET'])
def nothing_here():
    """
    No resource to be returned on GET request
    :return:
    """

    response = app.response_class(
        status=200,
    )

    return response


if __name__ == '__main__':
    # Test:

    """
    curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"text":"Our Domestic Bliss is our way of having fun with the audience’s expectations of what they think this doggy doodle doo will be,” Feig told PEOPLE. “It’s a slice of Saturday Evening Post, a dollop of Bad Housekeeping and a generous sprinkling of the Haunted Mansion on top.Without Carter","password":"xyz"}' \
  https://graph-processing-server-dot-graph-intelligence.appspot.com/infer

    """

    app.run(debug=False)
